# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: python:3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install OS dependencies
          command: |
            apt-get update && apt-get -y upgrade
            apt-get -y install graphviz
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/development.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest
  build_py2:
    docker:
      - image: python:2.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install OS dependencies
          command: |
            apt-get update && apt-get -y upgrade
            apt-get -y install graphviz
      - run:
          name: Install Python dependencies
          command: |
            python2.7 -m virtualenv venv
            . venv/bin/activate
            pip install -r requirements/development.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest
workflows:
  version: 2
  build_py2_py3:
    jobs:
      - build
      - build_py2
